# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constr.xdc

# IP: ip/blk_mem_gen_1/blk_mem_gen_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_1 || ORIG_REF_NAME==blk_mem_gen_1} -quiet] -quiet

# IP: ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_top_0_0_1/design_1_top_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_top_0_0 || ORIG_REF_NAME==design_1_top_0_0} -quiet] -quiet

# IP: ip/blk_mem_gen_1/blk_mem_gen_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_1 || ORIG_REF_NAME==blk_mem_gen_1} -quiet] -quiet

# IP: ip/blk_mem_gen_0/blk_mem_gen_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_0_1/design_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# XDC: ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc

# XDC: ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc

# XDC: ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc

# XDC: ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc

# XDC: bd/design_1/design_1_ooc.xdc
