# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/alexm/OneDrive/Documents/uni/CS351/test-project/test3/test3.srcs/sources_1/bd/design_1/ip/design_1_top_0_0/design_1_top_0_0.xci
# IP: The module: 'design_1_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Users/alexm/OneDrive/Documents/uni/CS351/test-project/test3/test3.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# IP: c:/Users/alexm/OneDrive/Documents/uni/CS351/test-project/test3/test3.srcs/sources_1/bd/design_1/ip/design_1_top_0_0/design_1_top_0_0.xci
# IP: The module: 'design_1_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Users/alexm/OneDrive/Documents/uni/CS351/test-project/test3/test3.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet
