domain_path: C:\Users\alexm\OneDrive\Documents\uni\CS351\test-project\test3\hello\zynq_fsbl\zynq_fsbl_bsp
app_src_dir: C:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\zynq_fsbl
template: zynq_fsbl
