domain_path: C:\Users\alexm\OneDrive\Documents\uni\CS351\test-project\test3\vitis_components\proj_plat\export\proj_plat\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
