@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Fri Apr 19 16:39:19 +0300 2024
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim tb_wah_behav -key {Behavioral:sim_1:Functional:tb_wah} -tclbatch tb_wah.tcl -view C:/Users/alexm/OneDrive/Documents/uni/CS351/test-project/pedal/misc/wah_testing.wcfg -view C:/Users/alexm/OneDrive/Documents/uni/CS351/test-project/pedal/misc/reverb_testing_pipelined.wcfg -view C:/Users/alexm/OneDrive/Documents/uni/CS351/test-project/pedal/misc/tb_reverb_behav.wcfg -view C:/Users/alexm/OneDrive/Documents/uni/CS351/test-project/pedal/misc/tb_wah_behav.wcfg -log simulate.log"
call xsim  tb_wah_behav -key {Behavioral:sim_1:Functional:tb_wah} -tclbatch tb_wah.tcl -view C:/Users/alexm/OneDrive/Documents/uni/CS351/test-project/pedal/misc/wah_testing.wcfg -view C:/Users/alexm/OneDrive/Documents/uni/CS351/test-project/pedal/misc/reverb_testing_pipelined.wcfg -view C:/Users/alexm/OneDrive/Documents/uni/CS351/test-project/pedal/misc/tb_reverb_behav.wcfg -view C:/Users/alexm/OneDrive/Documents/uni/CS351/test-project/pedal/misc/tb_wah_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
